package config

const (
	SignNormal              = "SignNormal"
	SignGesture             = "SignGesture"
	SignCode                = "SignCode"
	Courses                 = "Courses"
	SmtpUsername            = "SmtpUsername"
	SmtpPassword            = "SmtpPassword"
	NotifyTelegramBotChatId = "NotifyTelegramBotChatId"
	SignPhoto               = "SignPhoto"
	ChatId                  = "ChatId"
	NotifyEmail             = "NotifyEmail"
	NotifyPushPlusToken     = "NotifyPushPlusToken"
	SignDelay               = "SignDelay"
	SignEnable              = "SignEnable"
	CourseName              = "CourseName"
	WebHost                 = "WebHost"
	SmtpHost                = "SmtpHost"
	NotifyBarkApi           = "NotifyBarkApi"
	CourseId                = "CourseId"
	DefaultUsername         = "DefaultUsername"
	SmtpSSL                 = "SmtpSSL"
	SignLatitude            = "SignLatitude"
	ClassId                 = "ClassId"
	ClassName               = "ClassName"
	NotifyActive            = "NotifyActive"
	SignLongitude           = "SignLongitude"
	SignLocation            = "SignLocation"
	SignAddress             = "SignAddress"
	SignIp                  = "SignIp"
	Password                = "Password"
	SmtpPort                = "SmtpPort"
	NotifyTelegramBotToken  = "NotifyTelegramBotToken"
	NotifySign              = "NotifySign"
	WebPort                 = "WebPort"
	Username                = "Username"
	Fid                     = "Fid"
)
